name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build && ./gradlew shadowJar

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: App-Artifact
          path: |
            build/libs/*.jar
     #       ${{steps.sign_app.outputs.signedReleaseFile}}
    - name: Upload to Release
      uses: xresloader/upload-to-github-release@v1
      with:
        file: |
          build/libs/*.jar
      #    ${{steps.sign_app.outputs.signedReleaseFile}}
        name: ${{ github.pull_request_target }} ${{ github.GITHUB_BASE_REF }} ${{ github.run_id }}
        tag_name: ${{ github.run_id }} ${{ github.pull_request_target }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
